apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-grpc-rest-echo.fullname" . }}-echo-service
  labels:
  {{- include "k8s-grpc-rest-echo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.echoService.replicas }}
  selector:
    matchLabels:
      app: echo-service-app
    {{- include "k8s-grpc-rest-echo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: echo-service-app
      {{- include "k8s-grpc-rest-echo.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: echo-onfig-volume
          configMap:
            name: echo-configmap
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.echoService.echoService.image.repository }}:{{ .Values.echoService.echoService.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.echoService.echoService.imagePullPolicy }}
        volumeMounts:
        - name: echo-config-volume
          mountPath: /app/config
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        name: echo-service
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 50051
          name: grpc
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
        resources: {{- toYaml .Values.echoService.echoService.resources | nindent 10 }}