apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "k8s-grpc-rest-echo.fullname" . }}-grpc-ingress-gateway
  labels:
  {{- include "k8s-grpc-rest-echo.labels" . | nindent 4 }}
  annotations:
{{- with .Values.ingress.grpc.annotations }}
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{.Values.ingress.ingressClassName}}
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
      - path: {{.Values.ingress.grpc.pathPrefix}}(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{ include "k8s-grpc-rest-echo.fullname" . }}-grpc-echo-service'
            port:
              number: 50051

