apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-grpc-rest-echo.fullname" . }}-grpc-echo-service
  labels:
  {{- include "k8s-grpc-rest-echo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ingress.grpc.type }}
  selector:
    app: echo-service-app
  {{- include "k8s-grpc-rest-echo.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.ingress.grpc.ports | toYaml | nindent 2 }}